- hosts: workstation
  pre_tasks:
    - name: Welcome
      debug:
        msg: "Welcome!"

    - name: users | jay | create group
      tags: groups,jay,users
      become: true
      group:
        name: users
        state: present

    - name: users | jay | create user
      tags: insane131,sudo,users
      user:
        name: insane131 
        group: users
        groups: sudo
        state: present
#    comment: "Jay LaCroix"
#    password: "{{ jay_passwd }}"
        shell: /bin/bash


    - name: sudo-group
      tags: insane131,sudo,users
      become: true
      group:
        name: sudo
        state: present

    - name: Ensure sudo group has sudo privileges without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD:ALL"
        validate: "/usr/sbin/visudo -cf %s"
